version: "3"
services:
  webapp:
    container_name: hwendlessracer
    image: mattel/hwendlessracer
    build:
      context: .
    restart: always
    volumes:
      - ./:/usr/app
    env_file:
      - ./.env
    ports:
      - "6000:6000"
#    links:
#      - mongodb:mongodb
#    depends_on:
#      - mongodb

#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    volumes:
#      - ./data:/data/db
#    ports:
#      - "27017:27017"
